const char * cheat_ents =
	"{\n"
	"\"origin\" \"-256 352 -192\"\n"
	"\"netname\" \"gsrand_noclip_check2\"\n"
	"\"m_iszCheckValue\" \"2\"\n"
	"\"m_iszValueName\" \"button\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_noclip_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-224 288 -192\"\n"
	"\"m_iszNewValue\" \"3\"\n"
	"\"m_iszValueName\" \"movetype\"\n"
	"\"targetname\" \"gsrand_noclip_off\"\n"
	"\"target\" \"!activator\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-256 320 -192\"\n"
	"\"netname\" \"gsrand_noclip\"\n"
	"\"m_iszCheckValue\" \"32\"\n"
	"\"m_iszValueName\" \"button\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_noclip_check2\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-256 288 -192\"\n"
	"\"m_iszNewValue\" \"8\"\n"
	"\"m_iszValueName\" \"movetype\"\n"
	"\"targetname\" \"gsrand_noclip_on\"\n"
	"\"target\" \"!activator\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-256 288 -168\"\n"
	"\"m_iszNewValue\" \"19\"\n"
	"\"m_iszValueName\" \"renderfx\"\n"
	"\"targetname\" \"gsrand_noclip_on\"\n"
	"\"target\" \"!activator\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-256 288 -144\"\n"
	"\"m_iszNewValue\" \"1\"\n"
	"\"m_iszValueName\" \"renderamt\"\n"
	"\"targetname\" \"gsrand_noclip_on\"\n"
	"\"target\" \"!activator\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-256 288 -120\"\n"
	"\"m_iszNewValue\" \"255\"\n"
	"\"m_iszValueName\" \"rendercolor\"\n"
	"\"targetname\" \"gsrand_noclip_on\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"5\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-352 384 -192\"\n"
	"\"target\" \"gsrand_cheat_iter\"\n"
	"\"triggerstate\" \"1\"\n"
	"\"delay\" \"1\"\n"
	"\"spawnflags\" \"49\"\n"
	"\"classname\" \"trigger_auto\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-248 384 -192\"\n"
	"\"trigger_after_run\" \"gsrand_cheat_iter3\"\n"
	"\"name_filter\" \"gsrand_player\"\n"
	"\"targetname\" \"gsrand_cheat_iter2\"\n"
	"\"target\" \"gsrand_noclip_precheck\"\n"
	"\"triggerstate\" \"2\"\n"
	"\"delay_between_triggers\" \"0.0\"\n"
	"\"classname\" \"trigger_entity_iterator\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-320 384 -192\"\n"
	"\"trigger_after_run\" \"gsrand_cheat_iter2\"\n"
	"\"name_filter\" \"gsrand_player\"\n"
	"\"targetname\" \"gsrand_cheat_iter\"\n"
	"\"target\" \"gsrand_godmode_precheck\"\n"
	"\"delay_between_runs\" \"0.05\"\n"
	"\"run_mode\" \"2\"\n"
	"\"triggerstate\" \"1\"\n"
	"\"status_filter\" \"1\"\n"
	"\"classname\" \"trigger_entity_iterator\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-320 352 -192\"\n"
	"\"netname\" \"gsrand_godmode_check2\"\n"
	"\"m_iszCheckValue\" \"32\"\n"
	"\"m_iszValueName\" \"button\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_godmode_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-320 320 -192\"\n"
	"\"netname\" \"gsrand_godmode\"\n"
	"\"m_iszCheckValue\" \"4\"\n"
	"\"m_iszValueName\" \"button\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_godmode_check2\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-304 272 -192\"\n"
	"\"m_iszValueName\" \"takedamage\"\n"
	"\"targetname\" \"gsrand_godmode_on\"\n"
	"\"target\" \"!activator\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-304 272 -168\"\n"
	"\"m_iszNewValue\" \"19\"\n"
	"\"m_iszValueName\" \"renderfx\"\n"
	"\"targetname\" \"gsrand_godmode_on\"\n"
	"\"target\" \"!activator\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-304 272 -144\"\n"
	"\"m_iszNewValue\" \"1\"\n"
	"\"m_iszValueName\" \"renderamt\"\n"
	"\"targetname\" \"gsrand_godmode_on\"\n"
	"\"target\" \"!activator\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-304 272 -120\"\n"
	"\"m_iszValueType\" \"6\"\n"
	"\"m_iszNewValue\" \"255\"\n"
	"\"m_iszValueName\" \"rendercolor\"\n"
	"\"targetname\" \"gsrand_godmode_on\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"6\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-336 272 -144\"\n"
	"\"m_iszValueName\" \"rendercolor\"\n"
	"\"targetname\" \"gsrand_godmode_off\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"6\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-336 248 -144\"\n"
	"\"m_iszValueName\" \"renderamt\"\n"
	"\"targetname\" \"gsrand_render_off\"\n"
	"\"target\" \"!activator\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-336 248 -168\"\n"
	"\"m_iszValueName\" \"renderfx\"\n"
	"\"targetname\" \"gsrand_render_off\"\n"
	"\"target\" \"!activator\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-336 272 -192\"\n"
	"\"m_iszNewValue\" \"1\"\n"
	"\"m_iszValueName\" \"takedamage\"\n"
	"\"targetname\" \"gsrand_godmode_off\"\n"
	"\"target\" \"!activator\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-320 296 -192\"\n"
	"\"message\" \"gsrand_godmode_on\"\n"
	"\"netname\" \"gsrand_godmode_off\"\n"
	"\"m_iszValueName\" \"takedamage\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"targetname\" \"gsrand_godmode\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-336 272 -168\"\n"
	"\"netname\" \"gsrand_render_off\"\n"
	"\"m_iszCheckValue\" \"3\"\n"
	"\"m_iszValueName\" \"movetype\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"targetname\" \"gsrand_godmode_off\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-224 312 -168\"\n"
	"\"netname\" \"gsrand_render_off\"\n"
	"\"m_iszCheckValue\" \"1\"\n"
	"\"m_iszValueName\" \"takedamage\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"targetname\" \"gsrand_noclip_off\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-224 288 -168\"\n"
	"\"m_iszValueName\" \"rendercolor\"\n"
	"\"targetname\" \"gsrand_noclip_off\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"5\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 320 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_impulse101_spawn\"\n"
	"\"targetname\" \"gsrand_impulse101\"\n"
	"\"target\" \"gsrand_impulse101_spawn\"\n"
	"\"spawnflags\" \"128\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 352 -192\"\n"
	"\"netname\" \"gsrand_impulse101_check2\"\n"
	"\"m_iszCheckValue\" \"8192\"\n"
	"\"m_iszValueName\" \"button\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_impulse101_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 384 -192\"\n"
	"\"trigger_after_run\" \"gsrand_impulse101_phase2\"\n"
	"\"name_filter\" \"gsrand_player\"\n"
	"\"targetname\" \"gsrand_cheat_iter3\"\n"
	"\"target\" \"gsrand_impulse101_precheck\"\n"
	"\"triggerstate\" \"2\"\n"
	"\"delay_between_triggers\" \"0.05\"\n"
	"\"status_filter\" \"1\"\n"
	"\"classname\" \"trigger_entity_iterator\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 384 -168\"\n"
	"\"gsrand_impulse101_items\" \"0.01#2\"\n"
	"\"targetname\" \"gsrand_impulse101_phase2\"\n"
	"\"classname\" \"multi_manager\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 320 -96\"\n"
	"\"m_iszTriggerAfter\" \"gsrand_weapon_check\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_357\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 344 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_556\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 368 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_762\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 392 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_9mmbox\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 296 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_ARgrenades\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 296 -72\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_buckshot\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 296 -48\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_crossbow\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 272 -48\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_gaussclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 272 -72\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_rpgclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-360 224 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_sporeclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-312 224 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_sporeclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-312 272 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_sporeclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-336 272 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_sporeclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-312 296 -72\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_buckshot\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-312 296 -48\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_crossbow\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-360 272 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_sporeclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-384 272 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_sporeclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-408 272 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_sporeclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-408 248 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_sporeclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-384 248 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_sporeclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-360 248 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_sporeclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-336 248 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_sporeclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-312 248 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_sporeclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-336 224 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_sporeclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-384 224 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_sporeclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-408 224 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_sporeclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-336 296 -72\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_buckshot\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-360 296 -72\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_buckshot\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-384 296 -72\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_buckshot\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-408 296 -72\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_buckshot\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-312 272 -72\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_rpgclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-312 272 -48\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_gaussclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-336 272 -48\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_gaussclip\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-336 296 -48\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_crossbow\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-360 296 -48\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_crossbow\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-384 296 -48\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_crossbow\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-312 296 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_ARgrenades\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-336 296 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_ARgrenades\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-312 368 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_762\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-312 344 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_556\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-336 344 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_556\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-312 320 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_357\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-336 320 -96\"\n"
	"\"-movetype\" \"5\"\n"
	"\"m_iszCrtEntChildName\" \"gsrand_impulse101_items\"\n"
	"\"m_iszCrtEntChildClass\" \"ammo_357\"\n"
	"\"targetname\" \"gsrand_impulse101_spawn\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-40 40 -192\"\n"
	"\"message\" \"gsrand_give_crowbar\"\n"
	"\"m_iszCheckValue\" \"2\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-64 40 -192\"\n"
	"\"message\" \"gsrand_give_pistol\"\n"
	"\"m_iszCheckValue\" \"4\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-88 40 -192\"\n"
	"\"message\" \"gsrand_give_357\"\n"
	"\"m_iszCheckValue\" \"8\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-112 40 -192\"\n"
	"\"message\" \"gsrand_give_9mmAR\"\n"
	"\"m_iszCheckValue\" \"16\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-40 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_crowbar_s\"\n"
	"\"targetname\" \"gsrand_give_crowbar\"\n"
	"\"target\" \"gsrand_give_crowbar_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-40 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_crowbar\"\n"
	"\"targetname\" \"gsrand_give_crowbar_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-136 40 -192\"\n"
	"\"message\" \"gsrand_give_crossbow\"\n"
	"\"m_iszCheckValue\" \"64\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-160 40 -192\"\n"
	"\"message\" \"gsrand_give_shotgun\"\n"
	"\"m_iszCheckValue\" \"128\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-184 40 -192\"\n"
	"\"message\" \"gsrand_give_rpg\"\n"
	"\"m_iszCheckValue\" \"256\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-208 40 -192\"\n"
	"\"message\" \"gsrand_give_gauss\"\n"
	"\"m_iszCheckValue\" \"512\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-232 40 -192\"\n"
	"\"message\" \"gsrand_give_egon\"\n"
	"\"m_iszCheckValue\" \"1024\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-256 40 -192\"\n"
	"\"message\" \"gsrand_give_hornet\"\n"
	"\"m_iszCheckValue\" \"2048\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-280 40 -192\"\n"
	"\"message\" \"gsrand_give_grenade\"\n"
	"\"m_iszCheckValue\" \"4096\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-304 40 -192\"\n"
	"\"message\" \"gsrand_give_tripmine\"\n"
	"\"m_iszCheckValue\" \"8192\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-328 40 -192\"\n"
	"\"message\" \"gsrand_give_satchel\"\n"
	"\"m_iszCheckValue\" \"16384\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-352 40 -192\"\n"
	"\"message\" \"gsrand_give_snark\"\n"
	"\"m_iszCheckValue\" \"32768\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-376 40 -192\"\n"
	"\"message\" \"gsrand_give_uzi\"\n"
	"\"m_iszCheckValue\" \"131072\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-400 40 -192\"\n"
	"\"message\" \"gsrand_give_medkit\"\n"
	"\"m_iszCheckValue\" \"262144\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-424 40 -192\"\n"
	"\"message\" \"gsrand_give_wrench\"\n"
	"\"m_iszCheckValue\" \"1048576\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-448 40 -192\"\n"
	"\"message\" \"gsrand_give_grapple\"\n"
	"\"m_iszCheckValue\" \"4194304\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-472 40 -192\"\n"
	"\"message\" \"gsrand_give_sniper\"\n"
	"\"m_iszCheckValue\" \"8388608\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-496 40 -192\"\n"
	"\"message\" \"gsrand_give_saw\"\n"
	"\"m_iszCheckValue\" \"16777216\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-520 40 -192\"\n"
	"\"message\" \"gsrand_give_m16\"\n"
	"\"m_iszCheckValue\" \"33554432\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-544 40 -192\"\n"
	"\"message\" \"gsrand_give_spore\"\n"
	"\"m_iszCheckValue\" \"67108864\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-568 40 -192\"\n"
	"\"message\" \"gsrand_give_deagle\"\n"
	"\"m_iszCheckValue\" \"134217728\"\n"
	"\"m_iszValueName\" \"weapons\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_weapon_check\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-64 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_pistol_s\"\n"
	"\"targetname\" \"gsrand_give_pistol\"\n"
	"\"target\" \"gsrand_give_pistol_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-64 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_9mmhandgun\"\n"
	"\"targetname\" \"gsrand_give_pistol_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-88 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_357_s\"\n"
	"\"targetname\" \"gsrand_give_357\"\n"
	"\"target\" \"gsrand_give_357_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-88 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_357\"\n"
	"\"targetname\" \"gsrand_give_357_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-112 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_9mmAR_s\"\n"
	"\"targetname\" \"gsrand_give_9mmAR\"\n"
	"\"target\" \"gsrand_give_9mmAR_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-112 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_9mmAR\"\n"
	"\"targetname\" \"gsrand_give_9mmAR_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-136 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_crossbow_s\"\n"
	"\"targetname\" \"gsrand_give_crossbow\"\n"
	"\"target\" \"gsrand_give_crossbow_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-136 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_crossbow\"\n"
	"\"targetname\" \"gsrand_give_crossbow_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-160 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_shotgun_s\"\n"
	"\"targetname\" \"gsrand_give_shotgun\"\n"
	"\"target\" \"gsrand_give_shotgun_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-160 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_shotgun\"\n"
	"\"targetname\" \"gsrand_give_shotgun_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-232 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_egon_s\"\n"
	"\"targetname\" \"gsrand_give_egon\"\n"
	"\"target\" \"gsrand_give_egon_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-232 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_egon\"\n"
	"\"targetname\" \"gsrand_give_egon_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-208 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_gauss_s\"\n"
	"\"targetname\" \"gsrand_give_gauss\"\n"
	"\"target\" \"gsrand_give_gauss_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-184 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_rpg_s\"\n"
	"\"targetname\" \"gsrand_give_rpg\"\n"
	"\"target\" \"gsrand_give_rpg_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-184 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_rpg\"\n"
	"\"targetname\" \"gsrand_give_rpg_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-208 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_gauss\"\n"
	"\"targetname\" \"gsrand_give_gauss_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-304 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_tripmine_s\"\n"
	"\"targetname\" \"gsrand_give_tripmine\"\n"
	"\"target\" \"gsrand_give_tripmine_s\"\n"
	"\"spawnflags\" \"128\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-304 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_tripmine\"\n"
	"\"targetname\" \"gsrand_give_tripmine_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-280 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_grenade_s\"\n"
	"\"targetname\" \"gsrand_give_grenade\"\n"
	"\"target\" \"gsrand_give_grenade_s\"\n"
	"\"spawnflags\" \"128\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-256 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_hornet_s\"\n"
	"\"targetname\" \"gsrand_give_hornet\"\n"
	"\"target\" \"gsrand_give_hornet_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-256 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_hornetgun\"\n"
	"\"targetname\" \"gsrand_give_hornet_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-280 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_handgrenade\"\n"
	"\"targetname\" \"gsrand_give_grenade_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-376 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_uzi_s\"\n"
	"\"targetname\" \"gsrand_give_uzi\"\n"
	"\"target\" \"gsrand_give_uzi_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-376 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_uziakimbo\"\n"
	"\"targetname\" \"gsrand_give_uzi_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-352 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_snark_s\"\n"
	"\"targetname\" \"gsrand_give_snark\"\n"
	"\"target\" \"gsrand_give_snark_s\"\n"
	"\"spawnflags\" \"128\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-328 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_satchel_s\"\n"
	"\"targetname\" \"gsrand_give_satchel\"\n"
	"\"target\" \"gsrand_give_satchel_s\"\n"
	"\"spawnflags\" \"128\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-328 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_satchel\"\n"
	"\"targetname\" \"gsrand_give_satchel_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-352 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_snark\"\n"
	"\"targetname\" \"gsrand_give_snark_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-448 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_grapple_s\"\n"
	"\"targetname\" \"gsrand_give_grapple\"\n"
	"\"target\" \"gsrand_give_grapple_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-448 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_grapple\"\n"
	"\"targetname\" \"gsrand_give_grapple_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-424 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_wrench_s\"\n"
	"\"targetname\" \"gsrand_give_wrench\"\n"
	"\"target\" \"gsrand_give_wrench_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-400 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_medkit_s\"\n"
	"\"targetname\" \"gsrand_give_medkit\"\n"
	"\"target\" \"gsrand_give_medkit_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-400 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_medkit\"\n"
	"\"targetname\" \"gsrand_give_medkit_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-424 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_pipewrench\"\n"
	"\"targetname\" \"gsrand_give_wrench_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-520 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_m16_s\"\n"
	"\"targetname\" \"gsrand_give_m16\"\n"
	"\"target\" \"gsrand_give_m16_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-520 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_m16\"\n"
	"\"targetname\" \"gsrand_give_m16_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-496 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_saw_s\"\n"
	"\"targetname\" \"gsrand_give_saw\"\n"
	"\"target\" \"gsrand_give_saw_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-472 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_sniper_s\"\n"
	"\"targetname\" \"gsrand_give_sniper\"\n"
	"\"target\" \"gsrand_give_sniper_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-472 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_sniperrifle\"\n"
	"\"targetname\" \"gsrand_give_sniper_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-496 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_m249\"\n"
	"\"targetname\" \"gsrand_give_saw_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-544 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_spore_s\"\n"
	"\"targetname\" \"gsrand_give_spore\"\n"
	"\"target\" \"gsrand_give_spore_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-568 64 -192\"\n"
	"\"dmg\" \"0.0\"\n"
	"\"m_iszDstValueName\" \"origin\"\n"
	"\"m_iszSrcValueName\" \"origin\"\n"
	"\"netname\" \"!activator\"\n"
	"\"message\" \"gsrand_give_deagle_s\"\n"
	"\"targetname\" \"gsrand_give_deagle\"\n"
	"\"target\" \"gsrand_give_deagle_s\"\n"
	"\"classname\" \"trigger_copyvalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-568 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_eagle\"\n"
	"\"targetname\" \"gsrand_give_deagle_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-544 88 -192\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_sporelauncher\"\n"
	"\"targetname\" \"gsrand_give_spore_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-280 88 -168\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_handgrenade\"\n"
	"\"targetname\" \"gsrand_give_grenade_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-304 88 -168\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_tripmine\"\n"
	"\"targetname\" \"gsrand_give_tripmine_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-304 88 -144\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_tripmine\"\n"
	"\"targetname\" \"gsrand_give_tripmine_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-304 88 -120\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_tripmine\"\n"
	"\"targetname\" \"gsrand_give_tripmine_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-304 88 -96\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_tripmine\"\n"
	"\"targetname\" \"gsrand_give_tripmine_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-328 88 -168\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_satchel\"\n"
	"\"targetname\" \"gsrand_give_satchel_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-328 88 -144\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_satchel\"\n"
	"\"targetname\" \"gsrand_give_satchel_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-328 88 -120\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_satchel\"\n"
	"\"targetname\" \"gsrand_give_satchel_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-328 88 -96\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_satchel\"\n"
	"\"targetname\" \"gsrand_give_satchel_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-352 88 -168\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_snark\"\n"
	"\"targetname\" \"gsrand_give_snark_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-352 88 -144\"\n"
	"\"-spawnflags\" \"1024\"\n"
	"\"m_iszCrtEntChildClass\" \"weapon_snark\"\n"
	"\"targetname\" \"gsrand_give_snark_s\"\n"
	"\"classname\" \"trigger_createentity\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-336 296 -144\"\n"
	"\"message\" \"Godmode OFF\"\n"
	"\"channel\" \"1\"\n"
	"\"fxtime\" \"0.25\"\n"
	"\"holdtime\" \"0.99\"\n"
	"\"color2\" \"255 255 255\"\n"
	"\"color\" \"255 255 255\"\n"
	"\"y\" \"0.45\"\n"
	"\"x\" \"-1\"\n"
	"\"targetname\" \"gsrand_godmode_off\"\n"
	"\"spawnflags\" \"2\"\n"
	"\"classname\" \"game_text\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-312 296 -144\"\n"
	"\"message\" \"Godmode ON\"\n"
	"\"channel\" \"1\"\n"
	"\"fxtime\" \"0.25\"\n"
	"\"holdtime\" \"0.99\"\n"
	"\"color2\" \"255 255 255\"\n"
	"\"color\" \"255 255 255\"\n"
	"\"y\" \"0.45\"\n"
	"\"x\" \"-1\"\n"
	"\"targetname\" \"gsrand_godmode_on\"\n"
	"\"spawnflags\" \"2\"\n"
	"\"classname\" \"game_text\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-256 264 -144\"\n"
	"\"message\" \"Noclip ON\"\n"
	"\"channel\" \"1\"\n"
	"\"fxtime\" \"0.25\"\n"
	"\"holdtime\" \"0.99\"\n"
	"\"color2\" \"255 255 255\"\n"
	"\"color\" \"255 255 255\"\n"
	"\"y\" \"0.45\"\n"
	"\"x\" \"-1\"\n"
	"\"targetname\" \"gsrand_noclip_on\"\n"
	"\"spawnflags\" \"2\"\n"
	"\"classname\" \"game_text\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-232 264 -144\"\n"
	"\"message\" \"Noclip OFF\"\n"
	"\"channel\" \"1\"\n"
	"\"fxtime\" \"0.25\"\n"
	"\"holdtime\" \"0.99\"\n"
	"\"color2\" \"255 255 255\"\n"
	"\"color\" \"255 255 255\"\n"
	"\"y\" \"0.45\"\n"
	"\"x\" \"-1\"\n"
	"\"targetname\" \"gsrand_noclip_off\"\n"
	"\"spawnflags\" \"2\"\n"
	"\"classname\" \"game_text\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-232 320 -192\"\n"
	"\"message\" \"gsrand_noclip_off\"\n"
	"\"netname\" \"gsrand_noclip_on\"\n"
	"\"m_iszCheckValue\" \"3\"\n"
	"\"m_iszValueName\" \"movetype\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"targetname\" \"gsrand_noclip\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-232 320 -168\"\n"
	"\"m_iszNewValue\" \"60\"\n"
	"\"m_iszValueName\" \"team\"\n"
	"\"targetname\" \"gsrand_noclip\"\n"
	"\"target\" \"!activator\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-256 352 -168\"\n"
	"\"message\" \"gsrand_dec_skin\"\n"
	"\"netname\" \"gsrand_noclip_check\"\n"
	"\"m_iszValueName\" \"team\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"2\"\n"
	"\"targetname\" \"gsrand_noclip_precheck\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-232 352 -168\"\n"
	"\"m_iszValueType\" \"3\"\n"
	"\"m_iszNewValue\" \"1\"\n"
	"\"m_iszValueName\" \"team\"\n"
	"\"targetname\" \"gsrand_dec_skin\"\n"
	"\"target\" \"!activator\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-320 352 -168\"\n"
	"\"message\" \"gsrand_dec_skin\"\n"
	"\"netname\" \"gsrand_godmode_check\"\n"
	"\"m_iszValueName\" \"team\"\n"
	"\"m_iCheckType\" \"2\"\n"
	"\"targetname\" \"gsrand_godmode_precheck\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-320 296 -168\"\n"
	"\"m_iszNewValue\" \"60\"\n"
	"\"m_iszValueName\" \"team\"\n"
	"\"targetname\" \"gsrand_godmode\"\n"
	"\"target\" \"!activator\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 352 -168\"\n"
	"\"message\" \"gsrand_dec_skin\"\n"
	"\"netname\" \"gsrand_impulse101_check\"\n"
	"\"m_iszValueName\" \"team\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"2\"\n"
	"\"targetname\" \"gsrand_impulse101_precheck\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 320 -168\"\n"
	"\"m_iszNewValue\" \"60\"\n"
	"\"m_iszValueName\" \"team\"\n"
	"\"targetname\" \"gsrand_impulse101\"\n"
	"\"target\" \"!activator\"\n"
	"\"classname\" \"trigger_changevalue\"\n"
	"}\n"
	"{\n"
	"\"origin\" \"-288 336 -192\"\n"
	"\"netname\" \"gsrand_impulse101\"\n"
	"\"m_iszCheckValue\" \"32\"\n"
	"\"m_iszValueName\" \"button\"\n"
	"\"m_fCheckInterval\" \"0.1\"\n"
	"\"m_iCheckBehaviour\" \"3\"\n"
	"\"m_iCheckType\" \"6\"\n"
	"\"targetname\" \"gsrand_impulse101_check2\"\n"
	"\"target\" \"!activator\"\n"
	"\"spawnflags\" \"96\"\n"
	"\"classname\" \"trigger_condition\"\n"
	"}\n";